Fix map repetition
hpi-swa-teaching/SqueakMaps pull request #78
Opened 2022-07-21 12:50 UTC by LeoKohlenberg

Fixes #72

2022-07-21 16:14 UTC, Durborough requested changes
Hier ist leider ein nil check. Können wir versuchen, den loszuwerden?
`packages/SqueakMaps-TiledMaps.package/SMAMarker.class/instance/worldPos.st`


Wofür brauchen wir `packages/SqueakMaps-TiledMaps.package/SMATiledMapMorph.class/instance/duplicateAndDrawMarker.On..st`?

Zudem fehlen mir für ein paar Funktionen wie z.B `mouseMove: AnEvent` oder `maxWorldPosHeight`, `pixelSize`, `tileCorner` `zoomMin` noch Kommentare, da ist irgendwie sehr viel Mathe drin, die ich nicht auf den ersten Blick verstehe.

2022-07-23 14:18 UTC, LeoKohlenberg commented
> Hier ist leider ein nil check. Können wir versuchen, den loszuwerden? `packages/SqueakMaps-TiledMaps.package/SMAMarker.class/instance/worldPos.st` 
Ja, ich glaube durch das Refactoring des Markers von Tim entfällt der Check.

> Wofür brauchen wir `packages/SqueakMaps-TiledMaps.package/SMATiledMapMorph.class/instance/duplicateAndDrawMarker.On..st`?
Punkte auf der Welt werden ja mit einer worldPos zwischen 0 und 1 repräsentiert und wenn ich aber links und rechts hin und her scrolle, sind auch die "Nachbarwelten" sichtbar welche von -1 bis 0 bzw 1 bis 2 gehen. Wenn da auch die Marker sichtbar sein sollen, müssen die Marker auch in den "Nachbarwelten" gezeichnet werden.
 
> Zudem fehlen mir für ein paar Funktionen wie z.B `mouseMove: AnEvent` oder `maxWorldPosHeight`, `pixelSize`, `tileCorner` `zoomMin` noch Kommentare, da ist irgendwie sehr viel Mathe drin, die ich nicht auf den ersten Blick verstehe.
Das liegt halt zum Teil auch in der Natur der Sache, die Funktionen haben halt häufig einfach den Zweck Formeln darzustellen und Werte zu berechnen. Ich denke man wird sich immer in Ruhe in den Code einarbeiten müssen, wenn man damit was machen will und Kommentare, die einfach nur die Berechnungen nochmal in Worten erklären wären schlechter Stil. Aber ich geb dir auch Recht, die Methoden sind schon sehr abschreckend^^. Eine abstrakte Zusammenfassung der Methoden könnte man einfügen, da bin ich unentschlossen, ob einem das hilft, fänd ich aber akzeptabel.

2022-07-24 11:52 UTC, TimRiedel approved these changes

2022-07-25 10:14 UTC, LeoKohlenberg commented
Hab mal paar Kommentare hinzugefügt, passt das? @Durborough

2022-07-25 14:50 UTC, Durborough approved these changes
Kommentare finde ich super

2022-08-03 15:52 UTC, merged